---
- hosts: ALL_TF
  remote_user: sa
  tasks:
    - name: "check tf state"
      shell: sh /home/sa/sa-center/bin/checkTFStatus.sh "{{TF_CODES}}"
      register: returnVar

    - name: "show return msg"
      debug:
        var: returnVar.stdout_lines
- hosts: ALL_CSF
  remote_user: sa
  tasks:
    - name: "check csf state"
      shell: sh /home/sa/sa-center/bin/checkCsfStatus.sh "{{PORTS}}" "{{OUT_SIDE_IP}}"
      register: returnVar2

    - name: "show return msg"
      debug:
        var: returnVar2.stdout_lines
