---
- hosts: ALL_TF
  remote_user: sa
  tasks:
    - name: "start all TF"
      shell: sh /home/sa/sa-center/bin/start_tf_by_code.sh "{{TF_CODES}}"
- hosts: ALL_CSF
  remote_user: sa
  tasks:
    - name: "start all csf "
      shell: sh /home/sa/sa-center/bin/start_csf_by_ports.sh "{{OUT_SIDE_IP}}" "{{PORTS}}"

